data:
  data_dir: '/home/soroosh/Desktop/datasets/music/lmd_processed/'
  max_files: 2000
  max_len: 512
  n_jobs: 12
  instruments: ['piano', 'bass', 'drums', 'guitar', 'ensemble']


model:
  lr: 0.0001
  max_epochs: 1
  
  dropout: &dropout 0.1
  d_model: &d_model 512
  d_inner: &d_inner 1024
  n_layers: &n_layers 8
  n_heads: &n_heads 8
  activation: &activation gelu
  final_norm: &final_norm False
  
  attributes: &attributes ['ttype', 'position', 'tempo', 'chord', 'instrument', 'pitch', 'duration', 'velocity']
  n_tokens: &n_tokens
    ttype: 3
    position: 17
    tempo: 21
    chord: 133
    instrument: 17
    pitch: 128
    duration: 16
    velocity: 30
      
  emb_dims: &emb_dims
    ttype: 8
    position: 32
    tempo: 48
    chord: 128
    instrument: 32
    pitch: 128
    duration: 32
    velocity: 64
  
  embedding:
    d_model: *d_model
    dropout: *dropout
    attributes: *attributes
    n_tokens: *n_tokens
    max_len: 100000
    emb_dims: *emb_dims
      
  encoder:
    d_model: *d_model
    d_inner: *d_inner
    n_heads: *n_heads
    self_attention_type: linear
    is_decoder: False
    dropout: *dropout
    activation: *activation
    n_layers: *n_layers
    final_norm: *final_norm
    
  head:
    d_model: *d_model
    attributes: *attributes
    n_tokens: *n_tokens
    emb_dims: *emb_dims